#include "lws_obs_helpers.hpp"
#include "config.hpp"
#define LOG_TAG "[" PLUGIN_NAME "][obs]"
#include "log.hpp"

#include <obs.h>
#include <obs-module.h>
#include <util/config-file.h>
#ifdef ENABLE_FRONTEND_API
#include <obs-frontend-api.h>
#endif
#include <cstring>
#include "lws_settings.hpp"

ObsWsAuth lws_get_obs_ws_credentials()
{
	ObsWsAuth auth = {4455, ""}; // Default port

	LwsSettings s = lws_settings_load();
	auth.port = s.obs_port;
	auth.password = s.obs_password;

	LOGI("ObsWsAuth: Returning manual settings (Port: %d)", auth.port);
	return auth;
}

#ifdef ENABLE_FRONTEND_API
static obs_scene_t *get_current_scene()
{
    obs_source_t *cur = obs_frontend_get_current_scene();
    if (!cur)
        return nullptr;

    obs_scene_t *scn = obs_scene_from_source(cur);
    obs_source_release(cur);
    return scn;
}
#endif

bool lws_create_or_update_browser_source_in_current_scene(const QString &name,
                                                          const QString &url,
                                                          int width,
                                                          int height)
{
#ifdef ENABLE_FRONTEND_API
    obs_scene_t *scn = get_current_scene();
    if (!scn) {
        LOGW("No current scene");
        return false;
    }

    obs_data_t *settings = obs_data_create();
    obs_data_set_bool(settings, "is_local_file", false);
    obs_data_set_string(settings, "url", url.toUtf8().constData());
    obs_data_set_int(settings, "width", width);
    obs_data_set_int(settings, "height", height);
    obs_data_set_bool(settings, "shutdown", false);

    // Add tagging CSS properties
    QString css = QStringLiteral(
        "body {\n"
        "  background-color: rgba(0, 0, 0, 0);\n"
        "  margin: 0px auto;\n"
        "  overflow: hidden;\n"
        "  --local-webserver-refresh: 1;\n"
        "  --media-warp-bridge: 1;\n"
        "}\n"
        "/* Generated by Media Warp */\n"
    );
    obs_data_set_string(settings, "css", css.toUtf8().constData());

    struct Ctx { obs_data_t *settings; bool updated; };
    Ctx ctx{settings, false};

    obs_scene_enum_items(
        scn,
        [](obs_scene_t *, obs_sceneitem_t *item, void *param)->bool {
            auto *ctx = static_cast<Ctx*>(param);
            obs_source_t *src = obs_sceneitem_get_source(item);
            const char *n = obs_source_get_name(src);
            if (n && std::strcmp(n, ctx->settings ? obs_data_get_string(ctx->settings, "name") : "") == 0)
                return true;
            if (n && std::strcmp(n, obs_data_get_string(ctx->settings, "browser_name")) == 0)
                return true;
            return true;
        },
        &ctx);

    obs_source_t *existing = obs_get_source_by_name(name.toUtf8().constData());
    if (existing) {
        const char *id = obs_source_get_id(existing);
        if (id && std::strcmp(id, "browser_source") == 0) {
            obs_source_update(existing, settings);
            obs_source_release(existing);
            obs_data_release(settings);
            LOGI("Updated browser source '%s'", name.toUtf8().constData());
            return true;
        }
        obs_source_release(existing);
    }

    obs_source_t *br = obs_source_create("browser_source",
                                         name.toUtf8().constData(),
                                         settings, nullptr);
    obs_data_release(settings);

    if (!br) {
        LOGW("Failed to create browser_source (is Browser plugin installed?)");
        return false;
    }

    obs_sceneitem_t *item = obs_scene_add(scn, br);
    if (!item) {
        LOGW("Failed to add browser source to scene");
        obs_source_release(br);
        return false;
    }

    vec2 pos = {40.0f, 40.0f};
    obs_sceneitem_set_pos(item, &pos);

    obs_source_release(br);

    LOGI("Created browser source '%s' -> %s",
         name.toUtf8().constData(), url.toUtf8().constData());
    return true;
#else
    Q_UNUSED(name); Q_UNUSED(url); Q_UNUSED(width); Q_UNUSED(height);
    LOGW("Frontend API disabled; can't create browser source.");
    return false;
#endif
}

bool lws_refresh_browser_source_by_name(const QString &name)
{
#ifdef ENABLE_FRONTEND_API
    if (name.isEmpty())
        return false;

    obs_source_t *src = obs_get_source_by_name(name.toUtf8().constData());
    if (!src) {
        LOGW("Browser source '%s' not found", name.toUtf8().constData());
        return false;
    }

    const char *id = obs_source_get_id(src);
    if (!id || std::strcmp(id, "browser_source") != 0) {
        LOGW("Source '%s' is not a browser_source", name.toUtf8().constData());
        obs_source_release(src);
        return false;
    }

    obs_data_t *s = obs_source_get_settings(src);
    obs_source_update(src, s);
    obs_data_release(s);

    obs_source_release(src);

    LOGI("Refreshed browser source '%s'", name.toUtf8().constData());
    return true;
#else
    Q_UNUSED(name);
    LOGW("Frontend API disabled; can't refresh browser source.");
    return false;
#endif
}

#include <QRegularExpression>

void lws_refresh_all_tagged_browser_sources(int httpPort, int wsPort)
{
	struct Context {
		int hPort;
		int wPort;
	};
	Context ctx{httpPort, wsPort};

	obs_enum_sources(
		[](void *param, obs_source_t *source) -> bool {
			auto *ctx = static_cast<Context *>(param);

			const char *id = obs_source_get_id(source);
			if (!id || std::strcmp(id, "browser_source") != 0)
				return true;

			obs_data_t *settings = obs_source_get_settings(source);
			QString css = QString::fromUtf8(obs_data_get_string(settings, "css"));

			if (css.contains(QStringLiteral("--local-webserver-refresh: 1;"))) {
				bool modified = false;

				// 1. Update URL port
				QString url = QString::fromUtf8(obs_data_get_string(settings, "url"));
				// Matches http://127.0.0.1:PORT/ or http://localhost:PORT/
				QRegularExpression urlRegex(QStringLiteral(R"((http://(?:127\.0\.0\.1|localhost)):(\d+)(.*))"));
				QRegularExpressionMatch urlMatch = urlRegex.match(url);
				if (urlMatch.hasMatch()) {
					QString newUrl = urlMatch.captured(1) + ":" + QString::number(ctx->hPort) + urlMatch.captured(3);
					if (newUrl != url) {
						obs_data_set_string(settings, "url", newUrl.toUtf8().constData());
						modified = true;
					}
				}

				// CSS port variable update removed (V3 uses API discovery)

				if (modified) {
					obs_source_update(source, settings);
					LOGI("Updated and refreshed tagged source: %s", obs_source_get_name(source));
				} else {
					// Even if ports didn't change, the user clicked "Refresh", so force a refresh
					obs_source_update(source, settings);
					LOGI("Refreshed tagged source: %s", obs_source_get_name(source));
				}
			}

			obs_data_release(settings);
			return true;
		},
		&ctx);
}

void lws_emit_credentials_to_tagged_sources()
{
	ObsWsAuth auth = lws_get_obs_ws_credentials();

	// 1. Emit a global signal for other plugins/scripts to hear
	signal_handler_t *sh = obs_get_signal_handler();
	calldata_t cd_global = {0};
	calldata_set_int(&cd_global, "port", auth.port);
	calldata_set_string(&cd_global, "password", auth.password.toUtf8().constData());
	signal_handler_signal(sh, "media_warp_auth", &cd_global);
	calldata_free(&cd_global);

	// 2. Direct JS injection to tagged browser sources
	obs_data_t *auth_data = obs_data_create();
	obs_data_set_int(auth_data, "port", auth.port);
	obs_data_set_string(auth_data, "password", auth.password.toUtf8().constData());
	const char *jsonStr = obs_data_get_json(auth_data);

	obs_enum_sources(
		[](void *param, obs_source_t *source) -> bool {
			const char *jsonStr = static_cast<const char *>(param);

			const char *id = obs_source_get_id(source);
			if (!id || std::strcmp(id, "browser_source") != 0)
				return true;

			obs_data_t *settings = obs_source_get_settings(source);
			const char *css = obs_data_get_string(settings, "css");

			if (css && std::strstr(css, "--local-webserver-refresh: 1;")) {
				proc_handler_t *ph = obs_source_get_proc_handler(source);
				if (ph) {
					calldata_t cd = {0};
					calldata_init(&cd);
					calldata_set_string(&cd, "eventName", "obs_auth");
					calldata_set_string(&cd, "jsonString", jsonStr);
					proc_handler_call(ph, "javascript_event", &cd);
					calldata_free(&cd);
					LOGI("Emitted credentials to tagged source: %s", obs_source_get_name(source));
				}
			}

			obs_data_release(settings);
			return true;
		},
		(void *)jsonStr);

	obs_data_release(auth_data);
}
